# Google Cloud Build configuration for Android APK
steps:
  # Build the Android APK
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '-v', '$PWD:/workspace', '-w', '/workspace', 'openjdk:17-jdk-slim', 'bash', '-c', 'apt-get update && apt-get install -y wget unzip && wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip && unzip -q commandlinetools-linux-9477386_latest.zip && mkdir -p android-sdk/cmdline-tools && mv cmdline-tools android-sdk/cmdline-tools/latest && export ANDROID_HOME=/workspace/android-sdk && export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin && yes | sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools" && chmod +x gradlew && ./gradlew assembleDebug']
    
  # Copy APK to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'app/build/outputs/apk/debug/*.apk', 'gs://${_BUCKET_NAME}/']

# Substitutions for the build
substitutions:
  _BUCKET_NAME: 'your-bucket-name'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Artifacts to store
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/'
    paths: ['app/build/outputs/apk/debug/*.apk']

# Build timeout
timeout: '1200s'