workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.advancedsnake"
      java: 17
      node: 16
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Get Flutter packages
        script: |
          echo "Setting up Android project..."
      - name: Build APK with Gradle
        script: |
          # Clean and build debug APK
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false